services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server_MyMoney
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  api:
    build:
      context: ./api
    # command: dotnet run
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./api:/app
      - ./api/appsettings.Development.json:/app/appsettings.Development.json
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - mssql

volumes:
  mssql_data:
