services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: local_mssql_server_MyMoney
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

#  api:
#    build:
#      context: ./api
#    container_name: local_api_MyMoney
#    ports:
#      - "80:80"
#      - "5032:5032"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    volumes:
#      - ./api:/app
#      - ./api/appsettings.Development.json:/app/appsettings.Development.json
#    working_dir: /app
#    restart: unless-stopped
#    depends_on:
#      - mssql
#
#  frontend:
#    build:
#      context: ./frontend
#    container_name: local_frontend_MyMoney
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#    working_dir: /app
#    restart: unless-stopped
#    depends_on:
#      - api

volumes:
  mssql_data:
