services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile_dev.dockerfile
    volumes:
      - ./:/app
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - ENVIRONMENT=development
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${BACKEND_PORT}", "--reload"]
  